update workflow

diff --git a/.github/workflows/reusable-jdk-os-matrix.yml b/.github/workflows/reusable-jdk-os-matrix.yml
--- a/.github/workflows/reusable-jdk-os-matrix.yml
+++ b/.github/workflows/reusable-jdk-os-matrix.yml
@@ -57,10 +57,10 @@ jobs:
 
       - name: Print Current Workflows
         run: |
-          echo "Reusable Workflow:"
-          cat .github/workflow-logic/.github/workflows/reusable-jdk-os-matrix.yml
-          echo "Caller Workflow:"
-          cat .github/workflows/auto-jdk-os-matrix.yml
+          echo "--- Reusable Workflow: ---"
+          cat .github/workflow-logic/.github/workflows/reusable-jdk-os-matrix.yml || echo "::warning::Could not find Reusable Workflow file."
+          echo "--- Caller Workflow: ---"
+          cat .github/workflows/auto-jdk-os-matrix.yml || echo "::warning::Could not find Caller Workflow file."
 
       - name: Test
         run: mvn clean test
